const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');

const PORT = process.env.PORT || 3001;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY;
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;

const PAIRS = ["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT"];
const PL = {BTCUSDT:"BTC",ETHUSDT:"ETH",BNBUSDT:"BNB",SOLUSDT:"SOL",XRPUSDT:"XRP",DOGEUSDT:"DOGE",ADAUSDT:"ADA",AVAXUSDT:"AVAX"};

// Indicators
const ema=(d,p)=>{if(!d.length)return[];const k=2/(p+1);let e=d[0];return d.map(v=>(e=v*k+e*(1-k)));};
const sma=(d,p)=>d.map((_,i)=>{if(i<p-1)return null;let s=0;for(let j=i-p+1;j<=i;j++)s+=d[j];return s/p;});
function rsi(c,p=14){if(c.length<p+1)return Array(c.length).fill(50);const r=Array(c.length).fill(50);let ag=0,al=0;for(let i=1;i<=p;i++){const d=c[i]-c[i-1];if(d>0)ag+=d;else al-=d;}ag/=p;al/=p;r[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<c.length;i++){const d=c[i]-c[i-1];ag=(ag*(p-1)+(d>0?d:0))/p;al=(al*(p-1)+(d<0?-d:0))/p;r[i]=al===0?100:100-100/(1+ag/al);}return r;}
function bband(c,p=20,m=2){const s=sma(c,p);return s.map((v,i)=>{if(v===null)return{u:null,m:null,l:null};let sm=0;for(let j=i-p+1;j<=i;j++)sm+=(c[j]-v)**2;const sd=Math.sqrt(sm/p);return{u:v+m*sd,m:v,l:v-m*sd,sd};});}
function atr(cn,p=14){if(cn.length<2)return Array(cn.length).fill(0);const tr=cn.map((c,i)=>{if(i===0)return c.high-c.low;return Math.max(c.high-c.low,Math.abs(c.high-cn[i-1].close),Math.abs(c.low-cn[i-1].close));});return ema(tr,p);}
function adx(cn,p=14){if(cn.length<p*2)return{adx:Array(cn.length).fill(20),pDI:Array(cn.length).fill(25),mDI:Array(cn.length).fill(25)};const pDM=[],mDM=[],tr=[];for(let i=0;i<cn.length;i++){if(i===0){pDM.push(0);mDM.push(0);tr.push(cn[i].high-cn[i].low);continue;}const u=cn[i].high-cn[i-1].high,d=cn[i-1].low-cn[i].low;pDM.push(u>d&&u>0?u:0);mDM.push(d>u&&d>0?d:0);tr.push(Math.max(cn[i].high-cn[i].low,Math.abs(cn[i].high-cn[i-1].close),Math.abs(cn[i].low-cn[i-1].close)));}const a=ema(tr,p),sp=ema(pDM,p),sm2=ema(mDM,p);const pD=sp.map((v,i)=>a[i]?v/a[i]*100:0),mD=sm2.map((v,i)=>a[i]?v/a[i]*100:0);const dx=pD.map((v,i)=>{const s=v+mD[i];return s?Math.abs(v-mD[i])/s*100:0;});return{adx:ema(dx,p),pDI:pD,mDI:mD};}
function cci(cn,p=20){return cn.map((c,i)=>{if(i<p-1)return 0;const t=[];for(let j=i-p+1;j<=i;j++)t.push((cn[j].high+cn[j].low+cn[j].close)/3);const mn=t.reduce((a,b)=>a+b,0)/p;const md=t.reduce((a,b)=>a+Math.abs(b-mn),0)/p;return md?((c.high+c.low+c.close)/3-mn)/(0.015*md):0;});}

// Agent definitions
const AG={titan:{n:"Titan",tf:"4h",htf:"1d",s:"BB+EMA+RSI"},phantom:{n:"Phantom",tf:"4h",htf:"1d",s:"Short Seller"},reversal:{n:"Reversal",tf:"4h",htf:null,s:"Z-Score Reversion"},shield:{n:"Shield",tf:"4h",htf:null,s:"Hedge Overlay"},razor:{n:"Razor",tf:"1h",htf:"4h",s:"EMA Scalp"},grokker:{n:"Grokker",tf:"4h",htf:"1d",s:"Contrarian"},breakout:{n:"Breakout",tf:"4h",htf:"1d",s:"Range Escape"},fortress:{n:"Fortress",tf:"1d",htf:"1w",s:"ADX Macro"},comet:{n:"Comet",tf:"1d",htf:null,s:"Smart DCA"},pulse:{n:"Pulse",tf:"4h",htf:null,s:"CCI Cycles"},blitz:{n:"Blitz",tf:"1h",htf:"4h",s:"Momentum"}};

// Signal functions
function sigTitan(cn,cl,hCn,hCl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const b=bband(cl),e50=ema(cl,50),rs=rsi(cl),at=atr(cn);const bn=b[n];if(!bn?.m)return{s:"HOLD",c:0,r:"BB loading",ind:{}};let hB="neutral";if(hCl?.length>20){const he=ema(hCl,20),hr=rsi(hCl);hB=hCl[hCl.length-1]>he[he.length-1]&&hr[hr.length-1]>45?"bullish":hCl[hCl.length-1]<he[he.length-1]&&hr[hr.length-1]<55?"bearish":"neutral";}const ind={RSI:rs[n].toFixed(1),EMA50:e50[n].toFixed(2),BB_L:bn.l.toFixed(2),BB_U:bn.u.toFixed(2),Daily:hB};if(cl[n]<=bn.l&&cl[n]>e50[n]&&rs[n]<40&&rs[n]>rs[n-1]&&hB!=="bearish")return{s:"LONG",c:hB==="bullish"?.85:.65,r:"4h BB lower+EMA50 support. RSI "+rs[n].toFixed(1)+" turning up. Daily: "+hB,sl:cl[n]-1.5*at[n],tp:bn.m,ind};if(cl[n]>=bn.u&&cl[n]<e50[n]&&rs[n]>60&&rs[n]<rs[n-1]&&hB!=="bullish")return{s:"SHORT",c:hB==="bearish"?.85:.65,r:"4h BB upper below EMA50. RSI "+rs[n].toFixed(1)+". Daily: "+hB,sl:cl[n]+1.5*at[n],tp:bn.m,ind};return{s:"HOLD",c:0,r:"4h mid-band RSI "+rs[n].toFixed(1)+". Daily: "+hB,ind};}
function sigPhantom(cn,cl,hCn,hCl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const e9=ema(cl,9),e21=ema(cl,21),e50=ema(cl,50),rs=rsi(cl),at=atr(cn);let dB=false;if(hCl?.length>50){const he=ema(hCl,50);dB=hCl[hCl.length-1]<he[he.length-1];}const ind={RSI:rs[n].toFixed(1),EMA9:e9[n].toFixed(2),EMA21:e21[n].toFixed(2),Daily_Bear:dB?"Yes":"No"};if(e9[n]<e21[n]&&cl[n]<e50[n]&&rs[n]<45&&dB)return{s:"SHORT",c:.75,r:"4h bearish stack + daily down. RSI "+rs[n].toFixed(1),sl:e50[n],tp:cl[n]-1.5*at[n],ind};if(e9[n]<e21[n]&&!dB)return{s:"HOLD",c:0,r:"4h bearish but daily NOT confirming",ind};return{s:"HOLD",c:0,r:"No bearish structure",ind};}
function sigReversal(cn,cl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const sm=sma(cl,50);if(!sm[n])return{s:"HOLD",c:0,r:"SMA loading",ind:{}};let sum=0;for(let i=n-49;i<=n;i++)sum+=(cl[i]-sm[n])**2;const sd=Math.sqrt(sum/50);if(!sd)return{s:"HOLD",c:0,r:"No vol",ind:{}};const z=(cl[n]-sm[n])/sd,pz=n>0?(cl[n-1]-(sm[n-1]||sm[n]))/(sd||1):z;const ind={Z:z.toFixed(2),SMA50:sm[n].toFixed(2)};if(z<-2&&z>pz)return{s:"LONG",c:Math.min(1,Math.abs(z)/3),r:"4h Z="+z.toFixed(2)+" reverting up",sl:sm[n]-3*sd,tp:sm[n],ind};if(z>2&&z<pz)return{s:"SHORT",c:Math.min(1,Math.abs(z)/3),r:"4h Z="+z.toFixed(2)+" reverting down",sl:sm[n]+3*sd,tp:sm[n],ind};return{s:"HOLD",c:0,r:"Z "+z.toFixed(2)+" in range",ind};}
function sigRazor(cn,cl,hCn,hCl){const n=cl.length-1;if(n<20)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const e5=ema(cl,5),e13=ema(cl,13),rs=rsi(cl,9),at=atr(cn);let hT="neutral";if(hCl?.length>21){const he=ema(hCl,21);hT=he[he.length-1]>he[he.length-2]?"up":"down";}const ind={EMA5:e5[n].toFixed(2),EMA13:e13[n].toFixed(2),RSI9:rs[n].toFixed(1),"4h":hT};if(n>0&&e5[n]>e13[n]&&e5[n-1]<=e13[n-1]&&rs[n]>50&&rs[n]<75&&hT==="up")return{s:"LONG",c:.75,r:"1h bull cross. 4h UP",sl:cl[n]-at[n],tp:cl[n]+1.5*at[n],ind};if(n>0&&e5[n]<e13[n]&&e5[n-1]>=e13[n-1]&&rs[n]<50&&rs[n]>25&&hT==="down")return{s:"SHORT",c:.75,r:"1h bear cross. 4h DOWN",sl:cl[n]+at[n],tp:cl[n]-1.5*at[n],ind};return{s:"HOLD",c:0,r:"No 1h cross. 4h: "+hT,ind};}
function sigBreakout(cn,cl,hCn,hCl){const n=cl.length-1;if(n<25)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const hi=cn.slice(n-20,n).map(c=>c.high),lo=cn.slice(n-20,n).map(c=>c.low);const up=Math.max(...hi),low=Math.min(...lo);const at2=atr(cn),vol=cn[n].volume,avgV=cn.slice(n-20,n).reduce((a,c)=>a+c.volume,0)/20,vr=(vol/avgV).toFixed(1);const ind={"Hi":up.toFixed(2),"Lo":low.toFixed(2),Vol:vr+"x"};if(cl[n]>up&&vol>avgV*1.3&&at2[n]>at2[n-1])return{s:"LONG",c:.7,r:"4h breakout above "+up.toFixed(2)+". Vol "+vr+"x",sl:up-.5*at2[n],tp:cl[n]+(up-low),ind};if(cl[n]<low&&vol>avgV*1.3&&at2[n]>at2[n-1])return{s:"SHORT",c:.7,r:"4h breakdown below "+low.toFixed(2),sl:low+.5*at2[n],tp:cl[n]-(up-low),ind};return{s:"HOLD",c:0,r:"In range",ind};}
function sigFortress(cn,cl,hCn,hCl){const n=cl.length-1;if(n<30)return{s:"HOLD",c:0,r:"Warming up (need 30 daily)",ind:{}};const{adx:ax,pDI,mDI}=adx(cn);const e50=ema(cl,50),at2=atr(cn);let wk=false;if(hCl?.length>20){const we=ema(hCl,20);wk=hCl[hCl.length-1]>we[we.length-1];}const ind={ADX:ax[n].toFixed(1),"+DI":pDI[n].toFixed(1),"-DI":mDI[n].toFixed(1),Weekly:wk?"Bull":"No"};if(ax[n]>25&&pDI[n]>mDI[n]&&cl[n]>e50[n]&&ax[n]>ax[n-1]&&wk)return{s:"LONG",c:Math.min(1,ax[n]/50),r:"MACRO TREND. ADX "+ax[n].toFixed(1)+". Weekly confirms",sl:cl[n]-2*at2[n],tp:cl[n]+3*at2[n],ind};if(ax[n]>25&&mDI[n]>pDI[n]&&cl[n]<e50[n]&&ax[n]>ax[n-1])return{s:"SHORT",c:Math.min(1,ax[n]/50),r:"Daily downtrend ADX "+ax[n].toFixed(1),sl:cl[n]+2*at2[n],tp:cl[n]-3*at2[n],ind};return{s:"HOLD",c:0,r:"ADX "+ax[n].toFixed(1)+" waiting",ind};}
function sigPulse(cn,cl){const n=cl.length-1;if(n<25)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const cc=cci(cn),e50=ema(cl,50),sl=e50[n]-e50[Math.max(0,n-3)],at2=atr(cn);const ind={CCI:cc[n].toFixed(0),Slope:sl>0?"Up":"Down"};if(cc[n]>-100&&cc[n-1]<=-100&&sl>0)return{s:"LONG",c:.65,r:"4h CCI bull cycle",sl:cl[n]-1.5*at2[n],tp:cl[n]+2*at2[n],ind};if(cc[n]<100&&cc[n-1]>=100&&sl<0)return{s:"SHORT",c:.65,r:"4h CCI bear cycle",sl:cl[n]+1.5*at2[n],tp:cl[n]-2*at2[n],ind};return{s:"HOLD",c:0,r:"CCI "+cc[n].toFixed(0)+" no transition",ind};}
function sigGrokker(cn,cl,hCn,hCl){const n=cl.length-1;if(n<20)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const rs=rsi(cl),vol=cn[n].volume,avgV=cn.slice(Math.max(0,n-20),n).reduce((a,c)=>a+c.volume,0)/20,vr=(vol/avgV).toFixed(1),at2=atr(cn);let dRSI=50;if(hCl?.length>14){const dr=rsi(hCl);dRSI=dr[dr.length-1];}const ind={RSI_4h:rs[n].toFixed(1),RSI_D:dRSI.toFixed(1),Vol:vr+"x"};if(rs[n]<25&&vol>avgV*1.5&&rs[n]>rs[n-1]&&dRSI<35)return{s:"LONG",c:.8,r:"MULTI-TF FEAR. 4h RSI "+rs[n].toFixed(1)+" Daily "+dRSI.toFixed(1),sl:cl[n]-2*at2[n],tp:cl[n]+2.5*at2[n],ind};if(rs[n]>75&&vol>avgV*1.5&&rs[n]<rs[n-1]&&dRSI>65)return{s:"SHORT",c:.8,r:"MULTI-TF GREED fading",sl:cl[n]+2*at2[n],tp:cl[n]-2.5*at2[n],ind};return{s:"HOLD",c:0,r:"RSI 4h "+rs[n].toFixed(1)+" Daily "+dRSI.toFixed(1),ind};}
function sigComet(cn,cl,_h,_hc,tick){const n=cl.length-1;if(n<14)return{s:"HOLD",c:0,r:"Warming up",ind:{}};if(tick%10!==0)return{s:"HOLD",c:0,r:"DCA: "+(10-tick%10)+" cycles to buy",ind:{}};const rs=rsi(cl);let m=1;if(rs[n]<30)m=1.5;else if(rs[n]<40)m=1.25;else if(rs[n]>70)m=.5;else if(rs[n]>60)m=.75;return{s:"LONG",c:.3*m,r:"Daily DCA. RSI "+rs[n].toFixed(1)+" mult "+m+"x",ind:{RSI:rs[n].toFixed(1)}};}
function sigBlitz(cn,cl,hCn,hCl){const n=cl.length-1;if(n<10)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const vol=cn[n].volume,avgV=cn.slice(Math.max(0,n-10),n).reduce((a,c)=>a+c.volume,0)/10,vr=(vol/avgV).toFixed(1);const roc=(cl[n]-cl[Math.max(0,n-5)])/cl[Math.max(0,n-5)]*100;const body=Math.abs(cn[n].close-cn[n].open)/(cn[n].high-cn[n].low||1);let hUp=false;if(hCl?.length>21){const he=ema(hCl,21);hUp=he[he.length-1]>he[he.length-2];}const ind={Vol:vr+"x",ROC:roc.toFixed(2)+"%","4h":hUp?"Up":"Down"};if(vol>avgV*3&&roc>2&&roc<10&&body>.6&&hUp)return{s:"LONG",c:.65,r:"1h momentum+4h up. Vol "+vr+"x",sl:cl[n]*.97,tp:cl[n]*1.05,ind};return{s:"HOLD",c:0,r:"No momentum. Vol "+vr+"x",ind};}
const SIG={titan:sigTitan,phantom:sigPhantom,reversal:sigReversal,razor:sigRazor,breakout:sigBreakout,fortress:sigFortress,pulse:sigPulse,grokker:sigGrokker,comet:sigComet,blitz:sigBlitz,shield:()=>({s:"HEDGE",c:.5,r:"Auto-hedge",ind:{}})};

// Conductors
const CD={aegis:{n:"Aegis",db:-.08,ct:.75,ag:["titan","reversal","comet","shield","fortress","pulse"],w:{titan:.15,reversal:.12,comet:.08,shield:.08,fortress:.05,pulse:.05}},atlas:{n:"Atlas",db:-.15,ct:.55,ag:["titan","phantom","reversal","grokker","shield","razor"],w:{titan:.20,phantom:.15,reversal:.12,grokker:.10,shield:.10,razor:.08}},apex_c:{n:"Apex",db:-.25,ct:.45,ag:["titan","phantom","grokker","breakout","razor","blitz"],w:{titan:.22,phantom:.18,grokker:.15,breakout:.12,razor:.12,blitz:.11}},phantom_edge:{n:"Phantom Edge",db:-.35,ct:.35,ag:["titan","phantom","grokker","razor","breakout","blitz"],w:{titan:.22,phantom:.20,grokker:.18,razor:.15,breakout:.13,blitz:.12}}};

// State
const START_CAP=10000;let candles={},portfolios={},positions={},tradeLog=[],regime="ranging",tick=0,lastCycleTime=null,status="STARTING";
function initPortfolios(){Object.entries(CD).forEach(([id,c])=>{const as={};c.ag.forEach(a=>{as[a]={pnl:0,trades:0,wins:0,ls:"HOLD",lr:"",op:0};});portfolios[id]={cap:START_CAP,peak:START_CAP,agents:as,hist:[{t:Date.now(),v:START_CAP}],dd:0,cb:false,tc:0};});}

// Binance fetch
async function fetchCandles(initial=false){const tfs=new Set();Object.values(AG).forEach(a=>{tfs.add(a.tf);if(a.htf)tfs.add(a.htf);});tfs.add("4h");const limit=initial?100:3;for(const tf of tfs){if(!candles[tf])candles[tf]={};for(const pair of PAIRS){try{const res=await fetch("https://api.binance.com/api/v3/klines?symbol="+pair+"&interval="+tf+"&limit="+limit);const raw=await res.json();if(!raw?.length)continue;const data=raw.map(k=>({time:k[0],open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]}));if(initial){candles[tf][pair]=data;}else{if(!candles[tf][pair])candles[tf][pair]=[];const ex=candles[tf][pair];data.forEach(c=>{const idx=ex.findIndex(e=>e.time===c.time);if(idx>=0)ex[idx]=c;else ex.push(c);});if(ex.length>150)ex.splice(0,ex.length-150);}}catch(e){}await new Promise(r=>setTimeout(r,40));}}}

// Regime detection
function detectRegime(){const btc=candles?.["4h"]?.BTCUSDT;if(!btc||btc.length<20)return"ranging";const cl=btc.map(c=>c.close);const n=cl.length-1;const e8=ema(cl,8),e21=ema(cl,21),rs=rsi(cl);const pc=(cl[n]-cl[Math.max(0,n-12)])/cl[Math.max(0,n-12)];if(pc<-.08)return"crash";if(e8[n]>e21[n]&&rs[n]>50)return"bull";if(e8[n]<e21[n]&&rs[n]<50)return"bear";return"ranging";}

// Simulation cycle
function runCycle(){regime=detectRegime();const em=regime==="crash"?.2:regime==="bear"?.6:regime==="bull"?1.2:1;const nl=[];
  Object.entries(CD).forEach(([cId,cond])=>{if(!portfolios[cId])return;const port=portfolios[cId];const ags=port.agents;if(port.cb)return;
    cond.ag.forEach(aId=>{if(!ags[aId])return;const agent=AG[aId];const sigFn=SIG[aId];if(!sigFn)return;const agTF=agent.tf;const agHTF=agent.htf;
      const ps=PAIRS.map(pair=>{const cn=candles[agTF]?.[pair];if(!cn?.length||cn.length<20)return{pair,sc:0};const cl=cn.map(c=>c.close);const hCn=agHTF?candles[agHTF]?.[pair]:null;const hCl=hCn?.map(c=>c.close);const sig=aId==="comet"?sigFn(cn,cl,hCn,hCl,tick):sigFn(cn,cl,hCn,hCl);return{pair,sc:sig.c,sig,cn,cl};}).sort((a,b)=>b.sc-a.sc);
      const best=ps[0];if(!best?.sig)return;const pk=cId+"_"+aId+"_"+best.pair;const ex=positions[pk];const cp=best.cl[best.cl.length-1];const wt=cond.w[aId]||.1;
      ags[aId].ls=best.sig.s;ags[aId].lr=best.sig.r;ags[aId].lp=PL[best.pair];
      if(aId==="shield")return;
      if(ex){const pp=ex.dir==="long"?(cp-ex.entry)/ex.entry:(ex.entry-cp)/ex.entry;let sc=false,cr="";if(pp<-.025){sc=true;cr="Stop loss "+agTF+" "+(pp*100).toFixed(2)+"%";}if(pp>.05){sc=true;cr="Take profit "+agTF+" +"+(pp*100).toFixed(2)+"%";}if(best.sig.s==="HOLD"&&pp>.02){sc=true;cr="Signal faded locking +"+(pp*100).toFixed(2)+"%";}if((ex.dir==="long"&&best.sig.s==="SHORT")||(ex.dir==="short"&&best.sig.s==="LONG")){sc=true;cr="Signal reversed";}
        if(sc){const rp=pp*ex.size;port.cap+=rp;ags[aId].pnl+=rp;ags[aId].trades++;if(rp>0)ags[aId].wins++;ags[aId].op--;delete positions[pk];nl.push({t:Date.now(),cId,aId,pair:best.pair,act:"CLOSE",dir:ex.dir,pnl:rp,pp,reason:cr,price:cp,entry:ex.entry,size:ex.size,dur:Date.now()-ex.ot,ind:best.sig.ind,tf:agTF,htf:agHTF,agentName:agent.n});}return;}
      if(best.sig.s==="HOLD"||best.sig.s==="HEDGE")return;if(best.sig.c<cond.ct)return;
      const ap=Object.keys(positions).filter(k=>k.startsWith(cId+"_"+aId)).length;if(ap>=2)return;
      const dir=best.sig.s==="LONG"?"long":"short";const sz=port.cap*wt*em;if(sz<10)return;
      positions[pk]={entry:cp,size:sz,dir,ot:Date.now(),sl:best.sig.sl,tp:best.sig.tp};ags[aId].op=(ags[aId].op||0)+1;port.tc=(port.tc||0)+1;
      nl.push({t:Date.now(),cId,aId,pair:best.pair,act:"OPEN",dir,size:sz,reason:best.sig.r,price:cp,conf:best.sig.c,sl:best.sig.sl,tp:best.sig.tp,ind:best.sig.ind,strat:agent.s,tf:agTF,htf:agHTF,hold:agTF==="1d"||agTF==="1w"?"weeks":agTF==="4h"?"days":"hours",agentName:agent.n});
    });
    let up=0;Object.entries(positions).forEach(([k,p])=>{if(!k.startsWith(cId))return;const pts=k.split("_");const pair=pts[2];const agId=pts[1];const agTF=AG[agId]?.tf||"4h";const cp2=candles[agTF]?.[pair]?.[candles[agTF][pair].length-1]?.close;if(!cp2)return;up+=p.dir==="long"?(cp2-p.entry)/p.entry*p.size:(p.entry-cp2)/p.entry*p.size;});
    const tv=port.cap+up;port.peak=Math.max(port.peak,tv);port.dd=(tv-port.peak)/port.peak;port.cb=port.dd<=cond.db;port.hist=[...port.hist.slice(-200),{t:Date.now(),v:tv}];
  });
  if(nl.length){tradeLog=[...nl,...tradeLog].slice(0,500);}tick++;lastCycleTime=new Date().toISOString();}

// Persistence
async function saveState(){if(!supabase)return;try{const state={portfolios,positions,regime,tick,lastCycleTime,tradeLog:tradeLog.slice(0,100)};await supabase.from('simulation_state').upsert({id:'main',data:state,updated_at:new Date().toISOString()});console.log("["+new Date().toISOString()+"] Saved. Tick "+tick+" regime: "+regime);}catch(e){console.error('Save error:',e.message);}}
async function loadState(){if(!supabase)return false;try{const{data}=await supabase.from('simulation_state').select('data').eq('id','main').single();if(data?.data){portfolios=data.data.portfolios||{};positions=data.data.positions||{};regime=data.data.regime||"ranging";tick=data.data.tick||0;tradeLog=data.data.tradeLog||[];console.log("Loaded state: tick "+tick);return true;}}catch(e){console.log('Fresh start');}return false;}

// Main loop
async function cycle(){try{await fetchCandles(tick===0);runCycle();await saveState();const pr=candles["4h"]?.BTCUSDT;const btcP=pr?pr[pr.length-1].close:0;console.log("[Tick "+tick+"] "+regime+" BTC:$"+btcP.toFixed(0)+" pos:"+Object.keys(positions).length);}catch(e){console.error('Cycle error:',e.message);}}

// Express API
const app=express();app.use(cors());
app.get('/',(req,res)=>res.json({status,tick,regime,lastCycleTime,uptime:process.uptime()}));
app.get('/api/state',(req,res)=>{const prices={};PAIRS.forEach(p=>{const d=candles["4h"]?.[p];if(d?.length)prices[p]=d[d.length-1].close;});res.json({portfolios,positions,regime,tick,lastCycleTime,status,prices,agents:AG,conductors:CD,tradeLog:tradeLog.slice(0,100)});});
app.get('/api/trades',(req,res)=>{const c=req.query.conductor;const limit=Math.min(parseInt(req.query.limit)||50,200);let trades=tradeLog;if(c)trades=trades.filter(t=>t.cId===c);res.json({trades:trades.slice(0,limit),total:trades.length});});

// Start
async function start(){console.log('=== Agent League Backend ===');console.log('Supabase: '+(supabase?'Connected':'In-memory only'));const loaded=await loadState();if(!loaded){initPortfolios();console.log('Fresh portfolios');}status="LOADING";console.log('Fetching candles (1h,4h,1d,1w x 8 pairs)...');await fetchCandles(true);runCycle();await saveState();status="LIVE";console.log('=== LIVE Tick '+tick+' '+regime+' ===');setInterval(cycle,60000);app.listen(PORT,()=>console.log('API on port '+PORT));}
start().catch(e=>{console.error('Fatal:',e);process.exit(1);});
